language: python

python:
  - "3.7"
  - "3.8"
  - "nightly"

services:
  - docker

before_install:
  - docker build -t lovelace-engine .
  - docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 14714:14714 lovelace-engine
  - docker ps -a
  - git clone https://github.com/project-lovelace/lovelace-solutions.git
  - ln -s lovelace-solutions/python/ solutions

env:
  - LOVELACE_SOLUTIONS_DIR=./solutions/

install:
  - pip install -r requirements.txt

script:
  - pytest
